---
- name: "Download Vivado from url"
  get_url: 
    url: "{{ vivado_download_url }}"
    dest: "/tmp/vivado.tar.gz"
    owner: "{{ vivado_user }}"
    group: "{{ vivado_group }}"
  register: result
  until: result is success
  retries: 5
  delay: 2

- name: "Create {{ vivado_tmp_installation_dir }}/vivado directory"
  file: 
    path: "{{ vivado_tmp_installation_dir }}/vivado"
    state: directory

- name: "Unarchive /tmp/vivado.tar.g"
  unarchive: 
    src: "/tmp/vivado.tar.gz"
    remote_src: yes 
    dest: "{{ vivado_tmp_installation_dir }}/vivado"
    owner: "{{ vivado_user }}"
    group: "{{ vivado_group }}"
    extra_opts: [ --strip-components=1 ]

- name: "Remove old installation file"
  file: 
    path: "{{ vivado_tmp_installation_dir }}/install_config.txt"
    state: absent

- name: "Configure the installation file"
  template:
    src: install_config.txt.j2
    dest: "{{ vivado_tmp_installation_dir }}/install_config.txt"
    owner: "{{ vivado_user }}"
    group: "{{ vivado_group }}"
    mode: 0644

- name: "Install Vivado"
  command: "{{ vivado_tmp_installation_dir }}/vivado/xsetup --agree {{ vivado_licenses_agreement }} --batch Install --config {{ vivado_tmp_installation_dir}}/install_config.txt"

- name: "Change permisions for {{ vivado_installation_path }} directory"
  command: "chown -R {{ vivado_user }}:{{ vivado_group }} {{ vivado_installation_path }}"



    