---
- name: "Download Vivado from url"
  get_url: 
    url: "{{ download_url }}"
    dest: "/tmp/vivado.tar.gz"
    owner: "{{ vivado_user }}"
    group: "{{ vivado_group }}"
  register: result
  until: result|success
  retries: 5
  delay: 2

- name: "Create /tmp/vivado"
  file: 
    path: /tmp/vivado
    state: directory

- name: "Unarchive /tmp/vivado.tar.g"
  unarchive: 
    src: "/tmp/vivado.tar.gz"
    remote_src: yes 
    dest: "/home/{{ vivado_user }}"
    owner: "{{ vivado_user }}"
    group: "{{ vivado_group }}"
